name: style
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - abseil-cpp=20230802.0
  - absl-py=2.1.0
  - aiohttp=3.9.5
  - aiosignal=1.2.0
  - anyio=4.2.0
  - aom=3.6.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - async-timeout=4.0.3
  - attrs=23.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.6.2
  - blosc=1.21.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.3.11
  - cachetools=5.3.3
  - certifi=2024.2.2
  - cffi=1.16.0
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - comm=0.2.1
  - cryptography=42.0.5
  - cudatoolkit=11.3.1
  - dav1d=1.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - faiss-gpu=1.7.3
  - ffmpeg=4.3
  - freetype=2.12.1
  - frozenlist=1.4.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=2.29.0
  - google-auth-oauthlib=0.5.2
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - gtest=1.14.0
  - idna=3.7
  - imagecodecs=2023.1.23
  - imageio=2.33.1
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - intel-openmp=2023.1.0
  - jedi=0.18.1
  - jinja2=3.1.3
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jxrlib=1.1
  - krb5=1.20.1
  - lame=3.100
  - lazy_loader=0.3
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libaec=1.0.4
  - libavif=0.11.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.7.1
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libfaiss=1.7.3
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.11.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp-base=1.3.2
  - libzopfli=1.0.3
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - multidict=6.0.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.1
  - notebook-shim=0.2.3
  - numpy=1.26.4
  - numpy-base=1.26.4
  - oauthlib=3.2.2
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.13
  - overrides=7.4.0
  - packaging=23.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.0
  - platformdirs=3.10.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - protobuf=3.20.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pybind11-abi=4
  - pycparser=2.21
  - pygments=2.15.1
  - pyjwt=2.8.0
  - pyopenssl=24.0.0
  - pysocks=1.7.1
  - python=3.9.19
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.30.2
  - requests-oauthlib=1.3.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - rsa=4.7.2
  - scikit-image=0.22.0
  - scipy=1.13.0
  - send2trash=1.8.2
  - setuptools=69.5.1
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tbb=2021.8.0
  - tensorboard=2.12.1
  - tensorboard-data-server=0.7.0
  - tensorboard-plugin-wit=1.8.1
  - terminado=0.17.1
  - tifffile=2023.4.12
  - tinycss2=1.2.1
  - tk=8.6.14
  - tomli=2.0.1
  - torchvision=0.13.1
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - urllib3=2.2.1
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=2.3.8
  - wheel=0.43.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.9.3
  - zeromq=4.3.5
  - zfp=1.0.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - annotated-types==0.6.0
      - aplus==0.11.0
      - astropy==6.0.1
      - astropy-iers-data==0.2024.5.13.0.30.12
      - blake3==0.4.1
      - bqplot==0.12.43
      - branca==0.7.2
      - clip==1.0
      - cloudpickle==3.0.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - dask==2024.5.0
      - datasets==2.19.2
      - dill==0.3.8
      - dnspython==2.6.1
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - email-validator==2.1.1
      - fastapi==0.111.0
      - fastapi-cli==0.0.3
      - filelock==3.14.0
      - fonttools==4.51.0
      - frozendict==2.4.4
      - fsspec==2024.3.1
      - ftfy==6.2.0
      - future==1.0.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - h11==0.14.0
      - h5py==3.11.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.23.0
      - importlib-resources==6.4.0
      - ipdb==0.13.13
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - llvmlite==0.42.0
      - locket==1.0.0
      - markdown-it-py==3.0.0
      - matplotlib==3.8.4
      - mdurl==0.1.2
      - multiprocess==0.70.16
      - nltk==3.8.1
      - numba==0.59.1
      - opencv-python==4.9.0.80
      - orjson==3.10.3
      - pandas==2.2.2
      - partd==1.4.2
      - progressbar2==4.4.2
      - pyarrow==16.1.0
      - pyarrow-hotfix==0.6
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pyerfa==2.0.1.4
      - pyparsing==3.1.2
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - python-utils==3.8.2
      - pythreejs==2.4.2
      - regex==2024.5.10
      - requests==2.32.3
      - rich==13.7.1
      - scikit-learn==1.4.2
      - scikit-surprise==1.1.4
      - seaborn==0.13.2
      - sentry-sdk==2.1.1
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - smmap==5.0.1
      - starlette==0.37.2
      - tabulate==0.9.0
      - threadpoolctl==3.5.0
      - timm==0.6.12
      - toolz==0.12.1
      - tqdm==4.66.4
      - traittypes==0.2.1
      - typer==0.12.3
      - tzdata==2024.1
      - ujson==5.10.0
      - uvicorn==0.29.0
      - uvloop==0.19.0
      - vaex==4.17.0
      - vaex-astro==0.9.3
      - vaex-core==4.17.1
      - vaex-hdf5==0.14.1
      - vaex-jupyter==0.8.2
      - vaex-ml==0.18.3
      - vaex-server==0.9.0
      - vaex-viz==0.5.4
      - wandb==0.17.0
      - watchfiles==0.21.0
      - wcwidth==0.2.13
      - websockets==12.0
      - xarray==2024.5.0
      - xxhash==3.4.1
      - xyzservices==2024.4.0
